# Generated by Django 5.0.7 on 2024-07-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="historial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tiempo_creado", models.DateTimeField(auto_now_add=True)),
                ("inicio", models.CharField(max_length=50)),
                ("final", models.CharField(max_length=50)),
                ("poste_1", models.IntegerField(max_length=10)),
                ("poste_2", models.IntegerField(max_length=10)),
                ("poste_3", models.IntegerField(max_length=10)),
                ("notas", models.CharField(max_length=500)),
            ],
        ),
    ]
