# Generated by Django 5.0.7 on 2024-07-31 18:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "AppBussConecta",
            "0004_alter_historial_notas_alter_historial_poste_2_and_more",
        ),
    ]

    operations = []
